version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/var/lib/redis/data
  shop:
    image: shop
    restart: always
    environment:
      - SERVER_PORT=80
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_DB=0
      - REDIS_TIME_OUT=60000
    ports:
      - '1234:80'
    depends_on:
      - 'postgres'
      - 'redis'

volumes:
  postgres:
    driver: local
  redis:
    driver: local
