apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shop.fullname" . }}
  labels:
    {{ include "shop.labels" . | nindent 4 }}
data:
  serverPort: '8080'
  postgresHost: postgres-postgresql.postgres-production
  postgresPort: '5432'
  postgresDb: shop
  redisHost: redis-master.redis-production
  redisPort: '6379'