apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop.fullname" . }}
  labels:
    {{ include "shop.labels" . | nindent 4 }}
type: Opaque
data:
  postgresUsername: cG9zdGdyZXM=
  postgresPassword: cG9zdGdyZXM=
  redisPassword: cmVkaXM=