server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      database: ${REDIS_DB:0}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIME_OUT:60000}
management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus"]
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
